/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type InstantiateMsg = {}
export type ExecuteMsg =
  | {
      delegate: {
        amount: Uint128
        validator: string
      }
    }
  | {
      undelegate_from: {
        amount?: Uint128 | null
        validator: string
      }
    }
  | {
      undelegate_all: {}
    }
  | {
      redelegate: {
        amount?: Uint128 | null
        destination_validator: string
        source_validator: string
      }
    }
  | {
      set_withdraw_address: {
        new_withdraw_address: string
      }
    }
  | {
      withdraw_delegator_reward: {
        validator: string
      }
    }
  | {
      withdraw_all_rewards: {}
    }
export type Uint128 = string
export type QueryMsg = string
export type MigrateMsg = {}
export type StakingExecuteMsg = ExecuteMsg
