/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.6.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { useQuery, UseQueryOptions, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { AllAccountsResponse, Uint128, Expiration, Timestamp, Uint64, AllAllowancesResponse, AllowanceInfo, AllowanceResponse, BalanceResponse, Binary, DownloadLogoResponse, ExecuteMsg, Logo, EmbeddedLogo, InstantiateMsg, Cw20Coin, InstantiateMarketingInfo, MinterResponse, LogoInfo, Addr, MarketingInfoResponse, QueryMsg, TokenInfoResponse } from "../contracts/Cw20Contract";
import { Cw20QueryClient, Cw20Client } from "../contracts/Cw20Contract";
export interface Cw20DownloadLogoQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<DownloadLogoResponse | undefined, Error, DownloadLogoResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export function useCw20DownloadLogoQuery({
  client,
  options
}: Cw20DownloadLogoQuery) {
  return useQuery<DownloadLogoResponse | undefined, Error, DownloadLogoResponse, (string | undefined)[]>(["cw20DownloadLogo", client?.contractAddress], () => client ? client.downloadLogo() : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20MarketingInfoQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<MarketingInfoResponse | undefined, Error, MarketingInfoResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export function useCw20MarketingInfoQuery({
  client,
  options
}: Cw20MarketingInfoQuery) {
  return useQuery<MarketingInfoResponse | undefined, Error, MarketingInfoResponse, (string | undefined)[]>(["cw20MarketingInfo", client?.contractAddress], () => client ? client.marketingInfo() : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20AllAccountsQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<AllAccountsResponse | undefined, Error, AllAccountsResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useCw20AllAccountsQuery({
  client,
  args,
  options
}: Cw20AllAccountsQuery) {
  return useQuery<AllAccountsResponse | undefined, Error, AllAccountsResponse, (string | undefined)[]>(["cw20AllAccounts", client?.contractAddress, JSON.stringify(args)], () => client ? client.allAccounts({
    limit: args.limit,
    startAfter: args.startAfter
  }) : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20AllAllowancesQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<AllAllowancesResponse | undefined, Error, AllAllowancesResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
  args: {
    limit?: number;
    owner: string;
    startAfter?: string;
  };
}
export function useCw20AllAllowancesQuery({
  client,
  args,
  options
}: Cw20AllAllowancesQuery) {
  return useQuery<AllAllowancesResponse | undefined, Error, AllAllowancesResponse, (string | undefined)[]>(["cw20AllAllowances", client?.contractAddress, JSON.stringify(args)], () => client ? client.allAllowances({
    limit: args.limit,
    owner: args.owner,
    startAfter: args.startAfter
  }) : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20AllowanceQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<AllowanceResponse | undefined, Error, AllowanceResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
  args: {
    owner: string;
    spender: string;
  };
}
export function useCw20AllowanceQuery({
  client,
  args,
  options
}: Cw20AllowanceQuery) {
  return useQuery<AllowanceResponse | undefined, Error, AllowanceResponse, (string | undefined)[]>(["cw20Allowance", client?.contractAddress, JSON.stringify(args)], () => client ? client.allowance({
    owner: args.owner,
    spender: args.spender
  }) : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20MinterQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<MinterResponse | undefined, Error, MinterResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export function useCw20MinterQuery({
  client,
  options
}: Cw20MinterQuery) {
  return useQuery<MinterResponse | undefined, Error, MinterResponse, (string | undefined)[]>(["cw20Minter", client?.contractAddress], () => client ? client.minter() : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20TokenInfoQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<TokenInfoResponse | undefined, Error, TokenInfoResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export function useCw20TokenInfoQuery({
  client,
  options
}: Cw20TokenInfoQuery) {
  return useQuery<TokenInfoResponse | undefined, Error, TokenInfoResponse, (string | undefined)[]>(["cw20TokenInfo", client?.contractAddress], () => client ? client.tokenInfo() : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20BalanceQuery {
  client?: Cw20QueryClient;
  options?: Omit<UseQueryOptions<BalanceResponse | undefined, Error, BalanceResponse, (string | undefined)[]>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
  args: {
    address: string;
  };
}
export function useCw20BalanceQuery({
  client,
  args,
  options
}: Cw20BalanceQuery) {
  return useQuery<BalanceResponse | undefined, Error, BalanceResponse, (string | undefined)[]>(["cw20Balance", client?.contractAddress, JSON.stringify(args)], () => client ? client.balance({
    address: args.address
  }) : undefined, { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw20UploadLogoMutation {
  client: Cw20Client;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20UploadLogoMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20UploadLogoMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20UploadLogoMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.uploadLogo(fee, memo, funds), options);
}
export interface Cw20UpdateMarketingMutation {
  client: Cw20Client;
  msg: {
    description?: string;
    marketing?: string;
    project?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20UpdateMarketingMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20UpdateMarketingMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20UpdateMarketingMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateMarketing(msg, fee, memo, funds), options);
}
export interface Cw20UpdateMinterMutation {
  client: Cw20Client;
  msg: {
    newMinter: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20UpdateMinterMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20UpdateMinterMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20UpdateMinterMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateMinter(msg, fee, memo, funds), options);
}
export interface Cw20MintMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    recipient: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20MintMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20MintMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20MintMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.mint(msg, fee, memo, funds), options);
}
export interface Cw20BurnFromMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20BurnFromMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20BurnFromMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20BurnFromMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.burnFrom(msg, fee, memo, funds), options);
}
export interface Cw20SendFromMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    contract: string;
    msg: string;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20SendFromMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20SendFromMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20SendFromMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.sendFrom(msg, fee, memo, funds), options);
}
export interface Cw20TransferFromMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    owner: string;
    recipient: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20TransferFromMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20TransferFromMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20TransferFromMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.transferFrom(msg, fee, memo, funds), options);
}
export interface Cw20DecreaseAllowanceMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    expires?: Expiration;
    spender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20DecreaseAllowanceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20DecreaseAllowanceMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20DecreaseAllowanceMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.decreaseAllowance(msg, fee, memo, funds), options);
}
export interface Cw20IncreaseAllowanceMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    expires?: Expiration;
    spender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20IncreaseAllowanceMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20IncreaseAllowanceMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20IncreaseAllowanceMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.increaseAllowance(msg, fee, memo, funds), options);
}
export interface Cw20SendMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    contract: string;
    msg: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20SendMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20SendMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20SendMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.send(msg, fee, memo, funds), options);
}
export interface Cw20BurnMutation {
  client: Cw20Client;
  msg: {
    amount: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20BurnMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20BurnMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20BurnMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.burn(msg, fee, memo, funds), options);
}
export interface Cw20TransferMutation {
  client: Cw20Client;
  msg: {
    amount: string;
    recipient: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: readonly Coin[];
  };
}
export function useCw20TransferMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw20TransferMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw20TransferMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.transfer(msg, fee, memo, funds), options);
}
