/**
* This file was automatically generated by cosmwasm-typescript-gen@0.2.15.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the cosmwasm-typescript-gen generate command to regenerate this file.
*/

import { useQuery, UseQueryOptions } from "react-query";
import { Binary, InstantiateMsg, ModuleKind, Module, ModuleInfo, QueryEnabledModulesResponse, QueryModulesResponse, Uint64, QueryOsConfigResponse, QueryVersionsResponse, ContractVersion } from "./ManagerContract";
import { ManagerQueryClient } from "../contracts/ManagerContract";
export interface ManagerQueryOsConfigQuery {
  client: ManagerQueryClient;
  options?: UseQueryOptions<QueryOsConfigResponse, Error, QueryOsConfigResponse, (string | undefined)[]>;
}
export function useManagerQueryOsConfigQuery({
  client,
  options
}: ManagerQueryOsConfigQuery) {
  return useQuery<QueryOsConfigResponse, Error, QueryOsConfigResponse, (string | undefined)[]>(["managerQueryOsConfig", client.contractAddress], () => client.queryOsConfig(), options);
}
export interface ManagerQueryEnabledModulesQuery {
  client: ManagerQueryClient;
  options?: UseQueryOptions<QueryEnabledModulesResponse, Error, QueryEnabledModulesResponse, (string | undefined)[]>;
}
export function useManagerQueryEnabledModulesQuery({
  client,
  options
}: ManagerQueryEnabledModulesQuery) {
  return useQuery<QueryEnabledModulesResponse, Error, QueryEnabledModulesResponse, (string | undefined)[]>(["managerQueryEnabledModules", client.contractAddress], () => client.queryEnabledModules(), options);
}
export interface ManagerQueryModulesQuery {
  client: ManagerQueryClient;
  options?: UseQueryOptions<QueryModulesResponse, Error, QueryModulesResponse, (string | undefined)[]>;
  args: {
    names: string[];
  };
}
export function useManagerQueryModulesQuery({
  client,
  args,
  options
}: ManagerQueryModulesQuery) {
  return useQuery<QueryModulesResponse, Error, QueryModulesResponse, (string | undefined)[]>(["managerQueryModules", client.contractAddress], () => client.queryModules({
    names: args.names
  }), options);
}
export interface ManagerQueryVersionsQuery {
  client: ManagerQueryClient;
  options?: UseQueryOptions<QueryVersionsResponse, Error, QueryVersionsResponse, (string | undefined)[]>;
  args: {
    names: string[];
  };
}
export function useManagerQueryVersionsQuery({
  client,
  args,
  options
}: ManagerQueryVersionsQuery) {
  return useQuery<QueryVersionsResponse, Error, QueryVersionsResponse, (string | undefined)[]>(["managerQueryVersions", client.contractAddress], () => client.queryVersions({
    names: args.names
  }), options);
}
