/**
* This file was automatically generated by @abstract-money/ts-codegen@0.35.4.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { AssetEntry, Decimal, InstantiateMsg, ExecuteMsg, AccountTrace, ChainName, Uint128, AccountOdds, AccountId, Bet, AnsAsset, QueryMsg, MigrateMsg, Addr, BetsResponse, ConfigResponse, ListOddsResponse, OddsResponse, RoundStatus, RoundResponse, Coin } from "./Betting.types";
import { BettingAppQueryClient, BettingAppClient } from "./Betting.client";
export const bettingQueryKeys = {
  contract: ([{
    contract: "betting"
  }] as const),
  address: (contractAddress: string | undefined) => ([{ ...bettingQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  round: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{ ...bettingQueryKeys.address(contractAddress)[0],
    method: "round",
    args
  }] as const),
  odds: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{ ...bettingQueryKeys.address(contractAddress)[0],
    method: "odds",
    args
  }] as const),
  listOdds: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{ ...bettingQueryKeys.address(contractAddress)[0],
    method: "list_odds",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{ ...bettingQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  bets: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{ ...bettingQueryKeys.address(contractAddress)[0],
    method: "bets",
    args
  }] as const)
};
export const bettingQueries = {
  round: <TData = RoundResponse,>({
    client,
    options
  }: BettingRoundQuery<TData>): UseQueryOptions<RoundResponse, Error, TData> => ({
    queryKey: bettingQueryKeys.round(client?.moduleId),
    queryFn: () => client ? client.round() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  odds: <TData = OddsResponse,>({
    client,
    args,
    options
  }: BettingOddsQuery<TData>): UseQueryOptions<OddsResponse, Error, TData> => ({
    queryKey: bettingQueryKeys.odds(client?.moduleId, args),
    queryFn: () => client ? client.odds({
      teamId: args.teamId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  listOdds: <TData = ListOddsResponse,>({
    client,
    options
  }: BettingListOddsQuery<TData>): UseQueryOptions<ListOddsResponse, Error, TData> => ({
    queryKey: bettingQueryKeys.listOdds(client?.moduleId),
    queryFn: () => client ? client.listOdds() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: BettingConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: bettingQueryKeys.config(client?.moduleId),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  bets: <TData = BetsResponse,>({
    client,
    options
  }: BettingBetsQuery<TData>): UseQueryOptions<BetsResponse, Error, TData> => ({
    queryKey: bettingQueryKeys.bets(client?.moduleId),
    queryFn: () => client ? client.bets() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface BettingReactQuery<TResponse, TData = TResponse> {
  client: BettingAppQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface BettingBetsQuery<TData> extends BettingReactQuery<BetsResponse, TData> {}
export function useBettingBetsQuery<TData = BetsResponse>({
  client,
  options
}: BettingBetsQuery<TData>) {
  return useQuery<BetsResponse, Error, TData>(bettingQueryKeys.bets(client?.moduleId), () => client ? client.bets() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface BettingConfigQuery<TData> extends BettingReactQuery<ConfigResponse, TData> {}
export function useBettingConfigQuery<TData = ConfigResponse>({
  client,
  options
}: BettingConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(bettingQueryKeys.config(client?.moduleId), () => client ? client.config() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface BettingListOddsQuery<TData> extends BettingReactQuery<ListOddsResponse, TData> {}
export function useBettingListOddsQuery<TData = ListOddsResponse>({
  client,
  options
}: BettingListOddsQuery<TData>) {
  return useQuery<ListOddsResponse, Error, TData>(bettingQueryKeys.listOdds(client?.moduleId), () => client ? client.listOdds() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface BettingOddsQuery<TData> extends BettingReactQuery<OddsResponse, TData> {
  args: {
    teamId: AccountId;
  };
}
export function useBettingOddsQuery<TData = OddsResponse>({
  client,
  args,
  options
}: BettingOddsQuery<TData>) {
  return useQuery<OddsResponse, Error, TData>(bettingQueryKeys.odds(client?.moduleId, args), () => client ? client.odds({
    teamId: args.teamId
  }) : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface BettingRoundQuery<TData> extends BettingReactQuery<RoundResponse, TData> {}
export function useBettingRoundQuery<TData = RoundResponse>({
  client,
  options
}: BettingRoundQuery<TData>) {
  return useQuery<RoundResponse, Error, TData>(bettingQueryKeys.round(client?.moduleId), () => client ? client.round() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface BettingUpdateConfigMutation {
  client: BettingAppClient;
  msg: {
    rake?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBettingUpdateConfigMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BettingUpdateConfigMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BettingUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface BettingCloseRoundMutation {
  client: BettingAppClient;
  msg: {
    winner?: AccountId;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBettingCloseRoundMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BettingCloseRoundMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BettingCloseRoundMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.closeRound(msg, fee, memo, funds), options);
}
export interface BettingDistributeWinningsMutation {
  client: BettingAppClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBettingDistributeWinningsMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BettingDistributeWinningsMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BettingDistributeWinningsMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.distributeWinnings(fee, memo, funds), options);
}
export interface BettingPlaceBetMutation {
  client: BettingAppClient;
  msg: {
    bet: Bet;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBettingPlaceBetMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BettingPlaceBetMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BettingPlaceBetMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.placeBet(msg, fee, memo, funds), options);
}
export interface BettingUpdateAccountsMutation {
  client: BettingAppClient;
  msg: {
    toAdd: AccountOdds[];
    toRemove: AccountId[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBettingUpdateAccountsMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BettingUpdateAccountsMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BettingUpdateAccountsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateAccounts(msg, fee, memo, funds), options);
}
export interface BettingRegisterMutation {
  client: BettingAppClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useBettingRegisterMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, BettingRegisterMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, BettingRegisterMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.register(fee, memo, funds), options);
}