/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.11.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from '@tanstack/react-query'
import { ExecuteResult } from '@cosmjs/cosmwasm-stargate'
import { StdFee } from '@cosmjs/amino'
import {
  AssetInfoBaseForAddr,
  Addr,
  AssetEntry,
  CheckValidityResponse,
  ConfigResponse,
  CosmosMsgForEmpty,
  BankMsg,
  Uint128,
  StakingMsg,
  DistributionMsg,
  WasmMsg,
  Binary,
  Coin,
  Empty,
  ExecuteMsg,
  UncheckedValueRef,
  Decimal,
  UncheckedProxyAsset,
  HoldingAmountResponse,
  HoldingValueResponse,
  InstantiateMsg,
  ValueRef,
  ProxyAssetConfigResponse,
  ProxyAsset,
  ContractEntry,
  ProxyAssetsResponse,
  QueryMsg,
  State,
  TotalValueResponse,
} from './Proxy.types'
import { ProxyQueryClient, ProxyClient } from './Proxy.client'
export const proxyQueryKeys = {
  contract: [
    {
      contract: 'proxy',
    },
  ] as const,
  address: (contractAddress: string | undefined) =>
    [{ ...proxyQueryKeys.contract[0], address: contractAddress }] as const,
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [{ ...proxyQueryKeys.address(contractAddress)[0], method: 'config', args }] as const,
  totalValue: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [{ ...proxyQueryKeys.address(contractAddress)[0], method: 'total_value', args }] as const,
  holdingValue: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [{ ...proxyQueryKeys.address(contractAddress)[0], method: 'holding_value', args }] as const,
  holdingAmount: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [{ ...proxyQueryKeys.address(contractAddress)[0], method: 'holding_amount', args }] as const,
  proxyAssetConfig: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [
      { ...proxyQueryKeys.address(contractAddress)[0], method: 'proxy_asset_config', args },
    ] as const,
  proxyAssets: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [{ ...proxyQueryKeys.address(contractAddress)[0], method: 'proxy_assets', args }] as const,
  checkValidity: (contractAddress: string | undefined, args?: Record<string, unknown>) =>
    [{ ...proxyQueryKeys.address(contractAddress)[0], method: 'check_validity', args }] as const,
}
export interface ProxyReactQuery<TResponse, TData = TResponse> {
  client: ProxyQueryClient | undefined
  options?: Omit<
    UseQueryOptions<TResponse, Error, TData>,
    "'queryKey' | 'queryFn' | 'initialData'"
  > & {
    initialData?: undefined
  }
}
export interface ProxyCheckValidityQuery<TData>
  extends ProxyReactQuery<CheckValidityResponse, TData> {}
export function useProxyCheckValidityQuery<TData = CheckValidityResponse>({
  client,
  options,
}: ProxyCheckValidityQuery<TData>) {
  return useQuery<CheckValidityResponse, Error, TData>(
    proxyQueryKeys.checkValidity(client?.contractAddress),
    () => (client ? client.checkValidity() : Promise.reject(new Error('Invalid client'))),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyProxyAssetsQuery<TData> extends ProxyReactQuery<ProxyAssetsResponse, TData> {
  args: {
    iterLimit?: number
    lastAssetName?: string
  }
}
export function useProxyProxyAssetsQuery<TData = ProxyAssetsResponse>({
  client,
  args,
  options,
}: ProxyProxyAssetsQuery<TData>) {
  return useQuery<ProxyAssetsResponse, Error, TData>(
    proxyQueryKeys.proxyAssets(client?.contractAddress, args),
    () =>
      client
        ? client.proxyAssets({
            iterLimit: args.iterLimit,
            lastAssetName: args.lastAssetName,
          })
        : Promise.reject(new Error('Invalid client')),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyProxyAssetConfigQuery<TData>
  extends ProxyReactQuery<ProxyAssetConfigResponse, TData> {
  args: {
    identifier: string
  }
}
export function useProxyProxyAssetConfigQuery<TData = ProxyAssetConfigResponse>({
  client,
  args,
  options,
}: ProxyProxyAssetConfigQuery<TData>) {
  return useQuery<ProxyAssetConfigResponse, Error, TData>(
    proxyQueryKeys.proxyAssetConfig(client?.contractAddress, args),
    () =>
      client
        ? client.proxyAssetConfig({
            identifier: args.identifier,
          })
        : Promise.reject(new Error('Invalid client')),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyHoldingAmountQuery<TData>
  extends ProxyReactQuery<HoldingAmountResponse, TData> {
  args: {
    identifier: string
  }
}
export function useProxyHoldingAmountQuery<TData = HoldingAmountResponse>({
  client,
  args,
  options,
}: ProxyHoldingAmountQuery<TData>) {
  return useQuery<HoldingAmountResponse, Error, TData>(
    proxyQueryKeys.holdingAmount(client?.contractAddress, args),
    () =>
      client
        ? client.holdingAmount({
            identifier: args.identifier,
          })
        : Promise.reject(new Error('Invalid client')),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyHoldingValueQuery<TData>
  extends ProxyReactQuery<HoldingValueResponse, TData> {
  args: {
    identifier: string
  }
}
export function useProxyHoldingValueQuery<TData = HoldingValueResponse>({
  client,
  args,
  options,
}: ProxyHoldingValueQuery<TData>) {
  return useQuery<HoldingValueResponse, Error, TData>(
    proxyQueryKeys.holdingValue(client?.contractAddress, args),
    () =>
      client
        ? client.holdingValue({
            identifier: args.identifier,
          })
        : Promise.reject(new Error('Invalid client')),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyTotalValueQuery<TData> extends ProxyReactQuery<TotalValueResponse, TData> {}
export function useProxyTotalValueQuery<TData = TotalValueResponse>({
  client,
  options,
}: ProxyTotalValueQuery<TData>) {
  return useQuery<TotalValueResponse, Error, TData>(
    proxyQueryKeys.totalValue(client?.contractAddress),
    () => (client ? client.totalValue() : Promise.reject(new Error('Invalid client'))),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyConfigQuery<TData> extends ProxyReactQuery<ConfigResponse, TData> {}
export function useProxyConfigQuery<TData = ConfigResponse>({
  client,
  options,
}: ProxyConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(
    proxyQueryKeys.config(client?.contractAddress),
    () => (client ? client.config() : Promise.reject(new Error('Invalid client'))),
    { ...options, enabled: !!client && (options?.enabled != undefined ? options.enabled : true) }
  )
}
export interface ProxyUpdateAssetsMutation {
  client: ProxyClient
  msg: {
    toAdd: UncheckedProxyAsset[]
    toRemove: string[]
  }
  args?: {
    fee?: number | StdFee | 'auto'
    memo?: string
    funds?: Coin[]
  }
}
export function useProxyUpdateAssetsMutation(
  options?: Omit<UseMutationOptions<ExecuteResult, Error, ProxyUpdateAssetsMutation>, 'mutationFn'>
) {
  return useMutation<ExecuteResult, Error, ProxyUpdateAssetsMutation>(
    ({ client, msg, args: { fee, memo, funds } = {} }) =>
      client.updateAssets(msg, fee, memo, funds),
    options
  )
}
export interface ProxyRemoveModuleMutation {
  client: ProxyClient
  msg: {
    module: string
  }
  args?: {
    fee?: number | StdFee | 'auto'
    memo?: string
    funds?: Coin[]
  }
}
export function useProxyRemoveModuleMutation(
  options?: Omit<UseMutationOptions<ExecuteResult, Error, ProxyRemoveModuleMutation>, 'mutationFn'>
) {
  return useMutation<ExecuteResult, Error, ProxyRemoveModuleMutation>(
    ({ client, msg, args: { fee, memo, funds } = {} }) =>
      client.removeModule(msg, fee, memo, funds),
    options
  )
}
export interface ProxyAddModuleMutation {
  client: ProxyClient
  msg: {
    module: string
  }
  args?: {
    fee?: number | StdFee | 'auto'
    memo?: string
    funds?: Coin[]
  }
}
export function useProxyAddModuleMutation(
  options?: Omit<UseMutationOptions<ExecuteResult, Error, ProxyAddModuleMutation>, 'mutationFn'>
) {
  return useMutation<ExecuteResult, Error, ProxyAddModuleMutation>(
    ({ client, msg, args: { fee, memo, funds } = {} }) => client.addModule(msg, fee, memo, funds),
    options
  )
}
export interface ProxyModuleActionMutation {
  client: ProxyClient
  msg: {
    msgs: CosmosMsgForEmpty[]
  }
  args?: {
    fee?: number | StdFee | 'auto'
    memo?: string
    funds?: Coin[]
  }
}
export function useProxyModuleActionMutation(
  options?: Omit<UseMutationOptions<ExecuteResult, Error, ProxyModuleActionMutation>, 'mutationFn'>
) {
  return useMutation<ExecuteResult, Error, ProxyModuleActionMutation>(
    ({ client, msg, args: { fee, memo, funds } = {} }) =>
      client.moduleAction(msg, fee, memo, funds),
    options
  )
}
export interface ProxySetAdminMutation {
  client: ProxyClient
  msg: {
    admin: string
  }
  args?: {
    fee?: number | StdFee | 'auto'
    memo?: string
    funds?: Coin[]
  }
}
export function useProxySetAdminMutation(
  options?: Omit<UseMutationOptions<ExecuteResult, Error, ProxySetAdminMutation>, 'mutationFn'>
) {
  return useMutation<ExecuteResult, Error, ProxySetAdminMutation>(
    ({ client, msg, args: { fee, memo, funds } = {} }) => client.setAdmin(msg, fee, memo, funds),
    options
  )
}
