/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { Coin } from '@cosmjs/amino'
import { MsgExecuteContractEncodeObject } from '@cosmjs/cosmwasm-stargate'
import { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx'
import { toUtf8 } from '@cosmjs/encoding'

import {
  InstantiateMsg,
  ExecuteMsg,
  AssetInfoBaseForString,
  PoolAddressBaseForString,
  AssetEntry,
  PoolType,
  UniquePoolId,
  Action,
  Expiration,
  Timestamp,
  Uint64,
  UncheckedContractEntry,
  UncheckedChannelEntry,
  PoolMetadata,
  QueryMsg,
  DexAssetPairing,
  AssetFilter,
  AssetInfoFilter,
  ContractEntry,
  ContractFilter,
  ChannelEntry,
  ChannelFilter,
  AssetPairingFilter,
  PoolMetadataFilter,
  MigrateMsg,
  AssetInfoBaseForAddr,
  Addr,
  AssetInfoListResponse,
  AssetsResponse,
  AssetListResponse,
  ChannelListResponse,
  ChannelsResponse,
  ConfigResponse,
  ContractListResponse,
  ContractsResponse,
  OwnershipForString,
  PoolAddressBaseForAddr,
  PoolAddressListResponse,
  PoolReference,
  PoolMetadataListResponse,
  PoolMetadatasResponse,
  PoolsResponse,
  RegisteredDexesResponse,
} from './AnsHost.types'
export interface AnsHostMessage {
  contractAddress: string
  sender: string
  updateContractAddresses: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedContractEntry[][]
      toRemove: UncheckedContractEntry[]
    },
    _funds?: Coin[]
  ) => MsgExecuteContractEncodeObject
  updateAssetAddresses: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[][]
      toRemove: string[]
    },
    _funds?: Coin[]
  ) => MsgExecuteContractEncodeObject
  updateChannels: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedChannelEntry[][]
      toRemove: UncheckedChannelEntry[]
    },
    _funds?: Coin[]
  ) => MsgExecuteContractEncodeObject
  updateDexes: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[]
      toRemove: string[]
    },
    _funds?: Coin[]
  ) => MsgExecuteContractEncodeObject
  updatePools: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: PoolAddressBaseForString[][]
      toRemove: UniquePoolId[]
    },
    _funds?: Coin[]
  ) => MsgExecuteContractEncodeObject
  updateOwnership: (action: Action, _funds?: Coin[]) => MsgExecuteContractEncodeObject
}
export class AnsHostMessageComposer implements AnsHostMessage {
  sender: string
  contractAddress: string

  constructor(sender: string, contractAddress: string) {
    this.sender = sender
    this.contractAddress = contractAddress
    this.updateContractAddresses = this.updateContractAddresses.bind(this)
    this.updateAssetAddresses = this.updateAssetAddresses.bind(this)
    this.updateChannels = this.updateChannels.bind(this)
    this.updateDexes = this.updateDexes.bind(this)
    this.updatePools = this.updatePools.bind(this)
    this.updateOwnership = this.updateOwnership.bind(this)
  }

  updateContractAddresses = (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedContractEntry[][]
      toRemove: UncheckedContractEntry[]
    },
    _funds?: Coin[]
  ): MsgExecuteContractEncodeObject => {
    const msg = {
      update_contract_addresses: {
        to_add: toAdd,
        to_remove: toRemove,
      },
    }
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds,
      }),
    }
  }
  updateAssetAddresses = (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[][]
      toRemove: string[]
    },
    _funds?: Coin[]
  ): MsgExecuteContractEncodeObject => {
    const msg = {
      update_asset_addresses: {
        to_add: toAdd,
        to_remove: toRemove,
      },
    }
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds,
      }),
    }
  }
  updateChannels = (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedChannelEntry[][]
      toRemove: UncheckedChannelEntry[]
    },
    _funds?: Coin[]
  ): MsgExecuteContractEncodeObject => {
    const msg = {
      update_channels: {
        to_add: toAdd,
        to_remove: toRemove,
      },
    }
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds,
      }),
    }
  }
  updateDexes = (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[]
      toRemove: string[]
    },
    _funds?: Coin[]
  ): MsgExecuteContractEncodeObject => {
    const msg = {
      update_dexes: {
        to_add: toAdd,
        to_remove: toRemove,
      },
    }
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds,
      }),
    }
  }
  updatePools = (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: PoolAddressBaseForString[][]
      toRemove: UniquePoolId[]
    },
    _funds?: Coin[]
  ): MsgExecuteContractEncodeObject => {
    const msg = {
      update_pools: {
        to_add: toAdd,
        to_remove: toRemove,
      },
    }
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds,
      }),
    }
  }
  updateOwnership = (action: Action, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    const msg = {
      update_ownership: action,
    }
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify(msg)),
        funds: _funds,
      }),
    }
  }
}
