/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { Coin, StdFee } from '@cosmjs/amino'
import {
  CosmWasmClient,
  ExecuteResult,
  SigningCosmWasmClient,
} from '@cosmjs/cosmwasm-stargate'
import {
  Action,
  Addr,
  AssetEntry,
  AssetFilter,
  AssetInfoBaseForAddr,
  AssetInfoBaseForString,
  AssetInfoFilter,
  AssetInfoListResponse,
  AssetListResponse,
  AssetPairingFilter,
  AssetsResponse,
  ChannelEntry,
  ChannelFilter,
  ChannelListResponse,
  ChannelsResponse,
  ConfigResponse,
  ContractEntry,
  ContractFilter,
  ContractListResponse,
  ContractsResponse,
  DexAssetPairing,
  ExecuteMsg,
  Expiration,
  InstantiateMsg,
  MigrateMsg,
  OwnershipForString,
  PoolAddressBaseForAddr,
  PoolAddressBaseForString,
  PoolAddressListResponse,
  PoolMetadata,
  PoolMetadataFilter,
  PoolMetadataListResponse,
  PoolMetadatasResponse,
  PoolReference,
  PoolType,
  PoolsResponse,
  QueryMsg,
  RegisteredDexesResponse,
  Timestamp,
  Uint64,
  UncheckedChannelEntry,
  UncheckedContractEntry,
  UniquePoolId,
} from './AnsHost.types'
export interface AnsHostReadOnlyInterface {
  contractAddress: string
  config: () => Promise<ConfigResponse>
  assets: ({ names }: { names: string[] }) => Promise<AssetsResponse>
  assetList: ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: AssetFilter
    limit?: number
    startAfter?: string
  }) => Promise<AssetListResponse>
  assetInfos: ({
    infos,
  }: { infos: AssetInfoBaseForString[] }) => Promise<AssetsResponse>
  assetInfoList: ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: AssetInfoFilter
    limit?: number
    startAfter?: AssetInfoBaseForString
  }) => Promise<AssetInfoListResponse>
  contracts: ({
    entries,
  }: { entries: ContractEntry[] }) => Promise<ContractsResponse>
  contractList: ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: ContractFilter
    limit?: number
    startAfter?: ContractEntry
  }) => Promise<ContractListResponse>
  channels: ({
    entries,
  }: { entries: ChannelEntry[] }) => Promise<ChannelsResponse>
  channelList: ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: ChannelFilter
    limit?: number
    startAfter?: ChannelEntry
  }) => Promise<ChannelListResponse>
  registeredDexes: () => Promise<RegisteredDexesResponse>
  pools: ({
    pairings,
  }: { pairings: DexAssetPairing[] }) => Promise<PoolsResponse>
  poolList: ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: AssetPairingFilter
    limit?: number
    startAfter?: DexAssetPairing
  }) => Promise<PoolAddressListResponse>
  poolMetadatas: ({
    ids,
  }: { ids: UniquePoolId[] }) => Promise<PoolMetadatasResponse>
  poolMetadataList: ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: PoolMetadataFilter
    limit?: number
    startAfter?: UniquePoolId
  }) => Promise<PoolMetadataListResponse>
  ownership: () => Promise<OwnershipForString>
}
export class AnsHostQueryClient implements AnsHostReadOnlyInterface {
  client: CosmWasmClient
  contractAddress: string

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client
    this.contractAddress = contractAddress
    this.config = this.config.bind(this)
    this.assets = this.assets.bind(this)
    this.assetList = this.assetList.bind(this)
    this.assetInfos = this.assetInfos.bind(this)
    this.assetInfoList = this.assetInfoList.bind(this)
    this.contracts = this.contracts.bind(this)
    this.contractList = this.contractList.bind(this)
    this.channels = this.channels.bind(this)
    this.channelList = this.channelList.bind(this)
    this.registeredDexes = this.registeredDexes.bind(this)
    this.pools = this.pools.bind(this)
    this.poolList = this.poolList.bind(this)
    this.poolMetadatas = this.poolMetadatas.bind(this)
    this.poolMetadataList = this.poolMetadataList.bind(this)
    this.ownership = this.ownership.bind(this)
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {},
    })
  }
  assets = async ({ names }: { names: string[] }): Promise<AssetsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      assets: {
        names,
      },
    })
  }
  assetList = async ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: AssetFilter
    limit?: number
    startAfter?: string
  }): Promise<AssetListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      asset_list: {
        filter,
        limit,
        start_after: startAfter,
      },
    })
  }
  assetInfos = async ({
    infos,
  }: { infos: AssetInfoBaseForString[] }): Promise<AssetsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      asset_infos: {
        infos,
      },
    })
  }
  assetInfoList = async ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: AssetInfoFilter
    limit?: number
    startAfter?: AssetInfoBaseForString
  }): Promise<AssetInfoListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      asset_info_list: {
        filter,
        limit,
        start_after: startAfter,
      },
    })
  }
  contracts = async ({
    entries,
  }: { entries: ContractEntry[] }): Promise<ContractsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      contracts: {
        entries,
      },
    })
  }
  contractList = async ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: ContractFilter
    limit?: number
    startAfter?: ContractEntry
  }): Promise<ContractListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      contract_list: {
        filter,
        limit,
        start_after: startAfter,
      },
    })
  }
  channels = async ({
    entries,
  }: { entries: ChannelEntry[] }): Promise<ChannelsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      channels: {
        entries,
      },
    })
  }
  channelList = async ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: ChannelFilter
    limit?: number
    startAfter?: ChannelEntry
  }): Promise<ChannelListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      channel_list: {
        filter,
        limit,
        start_after: startAfter,
      },
    })
  }
  registeredDexes = async (): Promise<RegisteredDexesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      registered_dexes: {},
    })
  }
  pools = async ({
    pairings,
  }: { pairings: DexAssetPairing[] }): Promise<PoolsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pools: {
        pairings,
      },
    })
  }
  poolList = async ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: AssetPairingFilter
    limit?: number
    startAfter?: DexAssetPairing
  }): Promise<PoolAddressListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool_list: {
        filter,
        limit,
        start_after: startAfter,
      },
    })
  }
  poolMetadatas = async ({
    ids,
  }: { ids: UniquePoolId[] }): Promise<PoolMetadatasResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool_metadatas: {
        ids,
      },
    })
  }
  poolMetadataList = async ({
    filter,
    limit,
    startAfter,
  }: {
    filter?: PoolMetadataFilter
    limit?: number
    startAfter?: UniquePoolId
  }): Promise<PoolMetadataListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pool_metadata_list: {
        filter,
        limit,
        start_after: startAfter,
      },
    })
  }
  ownership = async (): Promise<OwnershipForString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership: {},
    })
  }
}
export interface AnsHostInterface extends AnsHostReadOnlyInterface {
  contractAddress: string
  sender: string
  updateContractAddresses: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedContractEntry[][]
      toRemove: UncheckedContractEntry[]
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[],
  ) => Promise<ExecuteResult>
  updateAssetAddresses: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[][]
      toRemove: string[]
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[],
  ) => Promise<ExecuteResult>
  updateChannels: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedChannelEntry[][]
      toRemove: UncheckedChannelEntry[]
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[],
  ) => Promise<ExecuteResult>
  updateDexes: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[]
      toRemove: string[]
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[],
  ) => Promise<ExecuteResult>
  updatePools: (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: PoolAddressBaseForString[][]
      toRemove: UniquePoolId[]
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[],
  ) => Promise<ExecuteResult>
  updateOwnership: (
    action: Action,
    fee?: number | StdFee | 'auto',
    memo?: string,
    _funds?: Coin[],
  ) => Promise<ExecuteResult>
}
export class AnsHostClient
  extends AnsHostQueryClient
  implements AnsHostInterface
{
  client: SigningCosmWasmClient
  sender: string
  contractAddress: string

  constructor(
    client: SigningCosmWasmClient,
    sender: string,
    contractAddress: string,
  ) {
    super(client, contractAddress)
    this.client = client
    this.sender = sender
    this.contractAddress = contractAddress
    this.updateContractAddresses = this.updateContractAddresses.bind(this)
    this.updateAssetAddresses = this.updateAssetAddresses.bind(this)
    this.updateChannels = this.updateChannels.bind(this)
    this.updateDexes = this.updateDexes.bind(this)
    this.updatePools = this.updatePools.bind(this)
    this.updateOwnership = this.updateOwnership.bind(this)
  }

  updateContractAddresses = async (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedContractEntry[][]
      toRemove: UncheckedContractEntry[]
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_contract_addresses: {
          to_add: toAdd,
          to_remove: toRemove,
        },
      },
      fee,
      memo,
      _funds,
    )
  }
  updateAssetAddresses = async (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[][]
      toRemove: string[]
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_asset_addresses: {
          to_add: toAdd,
          to_remove: toRemove,
        },
      },
      fee,
      memo,
      _funds,
    )
  }
  updateChannels = async (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: UncheckedChannelEntry[][]
      toRemove: UncheckedChannelEntry[]
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_channels: {
          to_add: toAdd,
          to_remove: toRemove,
        },
      },
      fee,
      memo,
      _funds,
    )
  }
  updateDexes = async (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: string[]
      toRemove: string[]
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_dexes: {
          to_add: toAdd,
          to_remove: toRemove,
        },
      },
      fee,
      memo,
      _funds,
    )
  }
  updatePools = async (
    {
      toAdd,
      toRemove,
    }: {
      toAdd: PoolAddressBaseForString[][]
      toRemove: UniquePoolId[]
    },
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_pools: {
          to_add: toAdd,
          to_remove: toRemove,
        },
      },
      fee,
      memo,
      _funds,
    )
  }
  updateOwnership = async (
    action: Action,
    fee: number | StdFee | 'auto' = 'auto',
    memo?: string,
    _funds?: Coin[],
  ): Promise<ExecuteResult> => {
    return await this.client.execute(
      this.sender,
      this.contractAddress,
      {
        update_ownership: action,
      },
      fee,
      memo,
      _funds,
    )
  }
}
